# Generated by Django 5.0.4 on 2024-04-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_pelicula_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=150)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.pelicula')),
            ],
        ),
    ]
