# Generated by Django 5.0.4 on 2024-04-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='pelicula',
            new_name='pelicula_id',
        ),
        migrations.RenameField(
            model_name='detallealquiler',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.RenameField(
            model_name='detallealquiler',
            old_name='pelicula',
            new_name='pelicula_id',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero',
            new_name='genero_id',
        ),
    ]
