# Generated by Django 5.0.4 on 2024-04-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_rename_pelicula_calificacion_pelicula_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallealquiler',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='detallealquiler',
            old_name='pelicula_id',
            new_name='pelicula',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='genero_id',
            new_name='genero',
        ),
    ]
