# Generated by Django 5.0.4 on 2024-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_rename_pelicula_id_calificacion_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealquiler',
            name='estado',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
